### ISSUE TITLE
Asset Loader cannot be patched

### ISSUE THREAD

**Issue by mccab22k** [WulfMarius/AssetLoader#1]
Hi,
having an issue with the asset loader which I think is related to the redux
![20181221093729_1](https://user-images.githubusercontent.com/36287726/50353026-2fb65f80-0504-11e9-8ae2-3b8b4bd27b1b.jpg)

**Comment by WulfMarius** [comment]
AssetLoader has been updated to 3.0.0 and is now compatible with TLD V1.44
